# Use Node.js with Alpine
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy frontend source code
COPY . .

# Expose port and start the React app
EXPOSE 3000
CMD ["npm", "run" ,"dev"]